test = {   'name': 'q4_5',
    'points': [0, 0.3333, 0.3333, 0.3334],
    'suites': [   {   'cases': [   {'code': '>>> assert q4_5 < 0\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert q4_5 < -200\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert q4_5 < -20000\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert q4_5 > -30000\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
